SYMBOLS_CONFIG = [
    
    {
        "symbol": "ETH/USDT",
        "weight": 0.4,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "5m",
        "para": [825, 1.2],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "DOGE/USDT",
        "weight": 0.2,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "30m",
        "para": [395, 1.4],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "BTC/USDT",
        "weight": 0.2,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "30m",
        "para": [575, 3.5],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "BNB/USDT",
        "weight": 0.2,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "4h",
        "para": [190, 2.6],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "LTC/USDT",
        "weight": 0.2,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "30m",
        "para": [525, 2.6],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "MASK/USDT",
        "weight": 0.2,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "4h",
        "para": [825, 1],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "DYDX/USDT",
        "weight": 0.2,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "15m",
        "para": [1945, 1],
        "slippage": 0.02,
        "volatility": 0.98,
    },


]