SYMBOLS_CONFIG = [
    
    # {
    #     "symbol": "ETH/USDT",
    #     "weight": 0.2,
    #     "leverage": 3,
    #     # "strategy": "real_signal_none",
    #     # "strategy": "real_signal_random",
    #     # "strategy": "real_signal_simple_bolling",
    #     "strategy": "real_signal_BollingDelay",
    #     # "level": "1h",
    #     "level": "1m",
    #     "para": [325, 1.8, 10],
    #     "slippage": 0.02,
    #     "volatility": 0.98,
    # },
    {
        "symbol": "DOGE/USDT",
        "weight": 0.1,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        # "strategy": "real_signal_simple_bolling",
        "strategy": "real_signal_BollingDelay",
        "level": "1m",
        "para": [10, 1.2, 0.15],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    # {
    #     "symbol": "BTC/USDT",
    #     "weight": 0.2,
    #     "leverage": 3,
    #     # "strategy": "real_signal_none",
    #     # "strategy": "real_signal_random",
    #     # "strategy": "real_signal_simple_bolling",
    #     "strategy": "real_signal_BollingDelay",
    #     # "level": "30m",
    #     "level": "1m",
    #     "para": [540, 3.5, 18],
    #     "slippage": 0.02,
    #     "volatility": 0.98,
    # },
    # {
    #     "symbol": "BNB/USDT",
    #     "weight": 0.2,
    #     "leverage": 3,
    #     # "strategy": "real_signal_none",
    #     # "strategy": "real_signal_random",
    #     # "strategy": "real_signal_simple_bolling",
    #     "strategy": "real_signal_BollingDelay",
    #     # "level": "30m",
    #     "level": "5m",
    #     "para": [690, 1.3, 3],
    #     "slippage": 0.02,
    #     "volatility": 0.98,
    # },
    # {
    #     "symbol": "LTC/USDT",
    #     "weight": 0.2,
    #     "leverage": 3,
    #     # "strategy": "real_signal_none",
    #     # "strategy": "real_signal_random",
    #     # "strategy": "real_signal_simple_bolling",
    #     "strategy": "real_signal_BollingDelay",
    #     # "level": "15m",
    #     "level": "1m",
    #     "para": [660, 2.1, 8],
    #     "slippage": 0.02,
    #     "volatility": 0.98,
    # },
    # {
    #     "symbol": "MASK/USDT",
    #     "weight": 0.05,
    #     "leverage": 3,
    #     # "strategy": "real_signal_none",
    #     "strategy": "real_signal_random",
    #     # "strategy": "real_signal_simple_bolling",
    #     "strategy": "real_signal_BollingDelay",
    #     "level": "5m",
    #     "para": [825, 1],
    #     "slippage": 0.02,
    #     "volatility": 0.98,
    # },
    # {
    #     "symbol": "DYDX/USDT",
    #     "weight": 0.05,
    #     "leverage": 3,
    #     # "strategy": "real_signal_none",
    #     "strategy": "real_signal_random",
    #     # "strategy": "real_signal_simple_bolling",
    #     "strategy": "real_signal_BollingDelay",
    #     "level": "5m",
    #     "para": [1945, 1],
    #     "slippage": 0.02,
    #     "volatility": 0.98,
    # },
    # {
    #     "symbol": "LINK/USDT",
    #     "weight": 0.05,
    #     "leverage": 3,
    #     # "strategy": "real_signal_none",
    #     "strategy": "real_signal_random",
    #     # "strategy": "real_signal_simple_bolling",
    #     "strategy": "real_signal_BollingDelay",
    #     "level": "5m",
    #     "para": [445, 4.2],
    #     "slippage": 0.02,
    #     "volatility": 0.98,
    # },
    # {
    #     "symbol": "XRP/USDT",
    #     "weight": 0.1,
    #     "leverage": 3,
    #     # "strategy": "real_signal_none",
    #     # "strategy": "real_signal_random",
    #     # "strategy": "real_signal_simple_bolling",
    #     "strategy": "real_signal_BollingDelay",
    #     # "level": "1h",
    #     "level": "5m",
    #     "para": [710, 1.6, 18],
    #     "slippage": 0.02,
    #     "volatility": 0.98,
    # },
    # {
    #     "symbol": "OP/USDT",
    #     "weight": 0.05,
    #     "leverage": 3,
    #     # "strategy": "real_signal_none",
    #     "strategy": "real_signal_random",
    #     # "strategy": "real_signal_simple_bolling",
    #     "strategy": "real_signal_BollingDelay",
    #     "level": "15m",
    #     "para": [490, 1.5],
    #     "slippage": 0.02,
    #     "volatility": 0.98,
    # },


]