SYMBOLS_CONFIG = [
    
    {
        "symbol": "ETH/USDT",
        "weight": 0.2,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "4h",
        "para": [180, 2.9],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "DOGE/USDT",
        "weight": 0.1,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "30m",
        "para": [395, 1.4],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "BTC/USDT",
        "weight": 0.2,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "30m",
        "para": [535, 3.5],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "BNB/USDT",
        "weight": 0.1,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "4h",
        "para": [190, 2.6],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "LTC/USDT",
        "weight": 0.05,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "30m",
        "para": [525, 2.6],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "MASK/USDT",
        "weight": 0.05,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "4h",
        "para": [825, 1],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "DYDX/USDT",
        "weight": 0.05,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "15m",
        "para": [1945, 1],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "LINK/USDT",
        "weight": 0.05,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "15m",
        "para": [445, 4.2],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "XRP/USDT",
        "weight": 0.05,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "4h",
        "para": [195, 1.5],
        "slippage": 0.02,
        "volatility": 0.98,
    },
    {
        "symbol": "OP/USDT",
        "weight": 0.05,
        "leverage": 3,
        # "strategy": "real_signal_none",
        # "strategy": "real_signal_random",
        "strategy": "real_signal_simple_bolling",
        "level": "15m",
        "para": [490, 1.5],
        "slippage": 0.02,
        "volatility": 0.98,
    },


]